import type { Creative } from "~/types";

export async function list(): Promise<Creative[]> {
  const data: Creative[] = [
    {
      id: "creative_001",
      craft_id: "CRAFT-2024-001",
      platform: "meta",
      session_id: "session_abc123",
      status: "active",
      error_message: null,
      created_at: "2024-12-01T10:00:00Z",
      updated_at: "2024-12-02T15:30:00Z",
      is_deleted: false,
      meta_creative: {
        id: 1,
        creative_id: "creative_001",
        meta_campaign_id: "123456789",
        meta_adset_id: "987654321",
        meta_adcreative_id: "456789123",
        meta_ad_id: "789123456",
        campaign_name: "Summer Campaign 2024",
        campaign_objective: "CONVERSIONS",
        campaign_daily_budget: 10000,
        adset_name: "Adset - Target Audience A",
        adset_billing_event: "IMPRESSIONS",
        adset_optimization_goal: "REACH",
        adset_bid_strategy: "LOWEST_COST_WITHOUT_CAP",
        adset_bid_amount: null,
        adset_daily_budget: 5000,
        adset_targeting_json: "{\"age_min\": 25, \"age_max\": 45}",
        ad_title: "Amazing Product Launch",
        ad_body: "Discover our new product line with exclusive discounts!",
        ad_website_url: "https://example.com/product",
        ad_call_to_action: "SHOP_NOW",
      },
    },
    {
      id: "creative_002",
      craft_id: "CRAFT-2024-002",
      platform: "meta",
      session_id: "session_def456",
      status: "paused",
      error_message: null,
      created_at: "2024-11-28T14:20:00Z",
      updated_at: "2024-12-01T09:15:00Z",
      is_deleted: false,
      meta_creative: {
        id: 2,
        creative_id: "creative_002",
        meta_campaign_id: "234567890",
        meta_adset_id: "876543210",
        meta_adcreative_id: "567890234",
        meta_ad_id: "890234567",
        campaign_name: "Holiday Special",
        campaign_objective: "LINK_CLICKS",
        campaign_daily_budget: 15000,
        adset_name: "Adset - Retargeting",
        adset_billing_event: "LINK_CLICKS",
        adset_optimization_goal: "LINK_CLICKS",
        adset_bid_strategy: "LOWEST_COST_WITH_BID_CAP",
        adset_bid_amount: 250,
        adset_daily_budget: 7500,
        adset_targeting_json: "{\"age_min\": 18, \"age_max\": 65}",
        ad_title: "Holiday Sale - Up to 50% Off",
        ad_body: "Limited time offer! Shop now and save big on all items.",
        ad_website_url: "https://example.com/holiday-sale",
        ad_call_to_action: "LEARN_MORE",
      },
    },
    {
      id: "creative_003",
      craft_id: "CRAFT-2024-003",
      platform: "meta",
      session_id: "session_ghi789",
      status: "active",
      error_message: null,
      created_at: "2024-12-02T08:45:00Z",
      updated_at: "2024-12-02T20:10:00Z",
      is_deleted: false,
      meta_creative: {
        id: 3,
        creative_id: "creative_003",
        meta_campaign_id: "345678901",
        meta_adset_id: "765432109",
        meta_adcreative_id: "678901345",
        meta_ad_id: "901345678",
        campaign_name: "Brand Awareness Q4",
        campaign_objective: "BRAND_AWARENESS",
        campaign_daily_budget: 20000,
        adset_name: "Adset - Lookalike Audience",
        adset_billing_event: "IMPRESSIONS",
        adset_optimization_goal: "IMPRESSIONS",
        adset_bid_strategy: "LOWEST_COST_WITHOUT_CAP",
        adset_bid_amount: null,
        adset_daily_budget: 10000,
        adset_targeting_json: "{\"age_min\": 21, \"age_max\": 55}",
        ad_title: "Join Our Community",
        ad_body: "Be part of something amazing. Connect with thousands of users.",
        ad_website_url: "https://example.com/community",
        ad_call_to_action: "SIGN_UP",
      },
    },
  ];
  return data;
}
